apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop

spec:
  replicas: 2
  selector:
    matchLabels:
      app: prestashop
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - image: prestashop/prestashop:8
          name: prestashop
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: prestashop
                  key: PRESTASHOP_DB_HOST
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: mariadb-presta
                  key: MYSQL_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-presta
                  key: MYSQL_USER
            - name: PS_CACHING_SYSTEM
              value: "CacheRedis"
            - name: PS_CACHE_ENABLED
              value: "1"
            - name: PS_CACHE_REDIS_SERVER
              valueFrom:
                secretKeyRef:
                  name: prestashop
                  key: PS_REDIS_HOST
            - name: PS_CACHE_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: prestashop
                  key: PS_REDIS_PORT
          volumeMounts:
            - name: prestashop-pv
              mountPath: /var/www/html
      volumes:
        - name: prestashop-pv
          persistentVolumeClaim:
            claimName: ps-pv-claim