apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prestashop
  namespace: prestashop
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: "vador-fans.lan"
      http:
        paths:
          - pathType: ImplementationSpecific
            path: "/eshop(/|$)(.*)"
            backend:
              service:
                name: prestashop
                port:
                  number: 80
