apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps-pv-claim
  labels:
    app: prestashop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn