apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-wordpress
  labels:
    app: mariadb-wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G