apiVersion: v1
kind: Service
metadata:
  name: mariadb-wordpress
  labels:
    app: wordpress

spec:
  selector:
    app: wordpress
    tier: mariadb-wordpress
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
      protocol: TCP