apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma
  namespace: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      component: pma
  template:
    metadata:
      labels:
        component: pma
    spec:
      containers:
      - name: pma
        image: phpmyadmin:5.2.1-apache
        env:
          - name: PMA_HOSTS
            valueFrom:
              secretKeyRef:
                key: PMA_HOSTS
                name: pma
          - name: PMA_VERBOSES
            valueFrom:
              secretKeyRef:
                key: PMA_VERBOSES
                name: pma
