apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pma
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: pma
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  ingressClassName: nginx
  rules:
    - host: "pma.vador-fans.lan"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: pma
                port:
                  number: 8000