apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress:6.2.1-apache
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_ROOT_PASSWORD
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: WORDPRESS_REDIS_HOST
            - name: WORDPRESS_REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: wordpress
                  key: WORDPRESS_REDIS_PORT
            - name: WORDPRESS_CONFIG_EXTRA
              value: | 
                define('WP_REDIS_HOST', "cache-service.cache.svc.cluster.local"); 
                define('WP_REDIS_PORT', 6379);
          volumeMounts:
            - name: wordpress-pv
              mountPath: /var/www/html
      volumes:
        - name: wordpress-pv
          persistentVolumeClaim:
            claimName: wp-pv-claim