apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  namespace: wordpress
type: Opaque
data:
  WORDPRESS_DB_HOST: bWFyaWFkYi13b3JkcHJlc3M=
  WORDPRESS_REDIS_HOST: cmVkaXM=
  WORDPRESS_REDIS_PORT: NjM3OQ==