apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-prestashop
  labels:
    name: mariadb-prestashop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G